import Navbar from "@/components/(dashboard)/User/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen overflow-hidden" style={{ overflowY: "hidden" }}>
      <nav>
        <Navbar />
      </nav>
      {children}
    </div>
  );
}
